# Generated by Django 3.1.1 on 2021-09-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0003_auto_20210827_0326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='used_invitation',
            new_name='used_invitations',
        ),
    ]
